In [202]:
import numpy as np
import random as rd
import pandas as pd
from typing import List
from collections import defaultdict

In [328]:
def checkFit(matrix:np.ndarray, sequence:int, extremity=False) -> List[tuple]:
    '''Verifica o espaço disponível para encaixe da aula.

    Parâmetros
    ----------
    matrix: Matriz da verificação com qualquer dimensões.
    sequence: Sequência da aulas. Ex: 3 aulas de matemática sequênciais.
    extremity: Explora somente os encaixes nas extremidades.
    Ex: 3 aulas sequênciais em 5 aulas -> [(0, 0), (0, 2)]
    a possibilidade das 3 aulas no meio serão excluídas: [(0, 1)].

    Retorno
    -------
    Um array de tuplas com as posições possíveis para o encaixe.
    '''
    temp, line, seq = [], 0, sequence
    for (x, y), value in np.ndenumerate(matrix):
        if line != x:
            line = x
            seq = sequence
        if value and seq > 0:
            seq = seq - 1
            if seq == 0:
                temp.append((x, y - (sequence - 1)))
        elif value and seq == 0 and not matrix[x, y - (sequence - 1)]:

            print(value, (x, y - (sequence - 1)))
            temp.append((x, y - (sequence - 1)))
    if extremity:
        flat = defaultdict(list)
        for x, y in temp:
            flat[x].append(y)
        newTemp = []
        for i in flat:
            newTemp.append((i, flat[i][0]))
            if flat[i][-1]:
                newTemp.append((i, flat[i][-1]))
        return newTemp
    return temp

matrix = np.array([
[1, 0, 0, 0, 1],
[1, 1, 1, 0, 1],
[0, 0, 0, 1, 0],
[1, 0, 0, 0, 0],
[1, 1, 1, 0, 0]])

checkFit(matrix, 2)

# matrix = np.ones((2,5), int)
# assert checkFit(matrix, 1) == [(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4)]
# assert checkFit(matrix, 2) == [(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3)]
# assert checkFit(matrix, 3) == [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2)]
# assert checkFit(matrix, 4) == [(0, 0), (0, 1), (1, 0), (1, 1)]
# assert checkFit(matrix, 5) == [(0, 0), (1, 0)]
# assert checkFit(matrix, 1, True) == [(0, 0), (0, 4), (1, 0), (1, 4)]
# assert checkFit(matrix, 2, True) == [(0, 0), (0, 3), (1, 0), (1, 3)]
# assert checkFit(matrix, 3, True) == [(0, 0), (0, 2), (1, 0), (1, 2)]
# assert checkFit(matrix, 4, True) == [(0, 0), (0, 1), (1, 0), (1, 1)]
# assert checkFit(matrix, 5, True) == [(0, 0), (1, 0)]

1 (1, 3)


[(0, 3), (1, 0), (1, 3), (4, 0)]

In [309]:
def fit(matrix:np.ndarray, sequence:int, extremity=False, fixed=False) -> bool:
    '''Encaixa as aulas na matriz e retorna True caso sucesso'''
    options = checkFit(matrix, sequence, extremity=extremity)
    #print(options)
    if options:
        which = 0
        if not fixed:
            which = rd.randint(0, len(options) - 1)
        fitting = options[which]
        print(fitting, sequence, options)
        print(matrix)
        matrix[
            fitting[0], 
            fitting[1]:fitting[1] + sequence
        ] = 0
        return True
    else:
        return False

matrix = np.ones((5,5), int)

Uma sequência de 2 aulas de português nas extremidades e com um total de 6 aulas. Quais posições?

In [234]:
fit(matrix, 2, extremity=True)
fit(matrix, 2, extremity=True)
fit(matrix, 2, extremity=True)
matrix

array([[1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1]])

Após, uma sequência de 3 aulas de matemática e com um total de 6 aulas. Quais posições?

In [235]:
fit(matrix, 3)
fit(matrix, 3)
matrix

array([[1, 1, 0, 0, 0],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0]])

In [310]:
def transform(matrix:np.ndarray, classes:list):
    count = 0
    while count < matrix.size:
        print('tentativa,', count)
        success = True
        mcopy = np.ones((5,5), int)
        for i,c in enumerate(classes):
            if not fit(mcopy, c):
                #print('false', mcopy)
                success = False
                print(count, '| Não foi possível encaixar', c, 'aulas, na posição', i)
                break
        #print('ok', mcopy)
        if success:
            print('ok')
            print(mcopy)
            #return mcopy
        count += 1
    
aulas = [2,2,3,3,3,1,1,2,3,2,1,2]
matrix = np.ones((5,5), int)
print(matrix.size, sum(aulas), len(aulas))
transform(matrix, aulas)
#matrix
#df = pd.DataFrame(matrix, columns=['Seg', 'Ter', 'Qua', 'Qui', 'Sex'])
#df

25 25 12
tentativa, 0
(0, 2) 2 [(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3), (3, 0), (3, 1), (3, 2), (3, 3), (4, 0), (4, 1), (4, 2), (4, 3)]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(2, 2) 2 [(0, 0), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3), (3, 0), (3, 1), (3, 2), (3, 3), (4, 0), (4, 1), (4, 2), (4, 3)]
[[1 1 0 0 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(3, 2) 3 [(0, 2), (1, 0), (1, 1), (1, 2), (2, 2), (3, 0), (3, 1), (3, 2), (4, 0), (4, 1), (4, 2)]
[[1 1 0 0 1]
 [1 1 1 1 1]
 [1 1 0 0 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(1, 2) 3 [(0, 2), (1, 0), (1, 1), (1, 2), (2, 2), (4, 0), (4, 1), (4, 2)]
[[1 1 0 0 1]
 [1 1 1 1 1]
 [1 1 0 0 1]
 [1 1 0 0 0]
 [1 1 1 1 1]]
(4, 1) 3 [(0, 2), (2, 2), (4, 0), (4, 1), (4, 2)]
[[1 1 0 0 1]
 [1 1 0 0 0]
 [1 1 0 0 1]
 [1 1 0 0 0]
 [1 1 1 1 1]]
(1, 0) 1 [(0, 0), (0, 1), (0, 4), (1, 0), (1, 1), (2, 0), (2, 1), (2, 4), (3, 0), (3, 1), (4, 0), (4, 